language: php
sudo: required
dist: trusty

php:
    - 7.1
    - 7.2
    - 7.3

addons:
  chrome: stable

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache
install:
    - cp .env.travis .env
    - composer install --no-progress --no-interaction --prefer-dist --no-suggest
    - mysql -e 'CREATE DATABASE homestead;'
    - php artisan key:generate

before_script:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve

script:
    - php artisan migrate:fresh --seed
    - php artisan storage:link
    # - php artisan optimize:clear #clear all caches
    # - php artisan config:cache
    # - php artisan route:cache
    # - php artisan view:cache
    - vendor/bin/phpunit
    - php artisan dusk

notifications:
    email: false