language: php

php:
    - 7.1
    - 7.2
    - 7.3

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install --no-progress --no-interaction --prefer-dist --no-suggest
    - mysql -e 'CREATE DATABASE homestead;'
    - cp .env.travis .env

script:
    - php artisan migrate:fresh --seed
    - php artisan storage:link
    - php artisan optimize:clear #clear all caches
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - vendor/bin/phpunit

notifications:
    email: false